# !/usr/bin/env python
# -*- coding: utf-8 -*-
url = 'http://csdqtjcag.lx901.com/ActivesManage/AddActity'
datas = '''{
    "act_type":2,
    "bonus_type":2,
    "ko_unique_1":0,
    "FName":"页面活动",
    "act_status":"",
    "FAuditBeginTime":"02:00:00",
    "FAuditEndTime":"02:00:00",
    "FIntervalTime":0,
    Content-Disposition: form-data; name="FActivityImage"; filename="images1.jfif"
Content-Type: image/jpeg:"",
    Content-Disposition: form-data; name="FActivityImageEnroll"; filename="images2.jfif"
Content-Type: image/jpeg:"",
    Content-Disposition: form-data; name="FActivityPhoneImage"; filename="images1.jfif"
Content-Type: image/jpeg:"",
    Content-Disposition: form-data; name="FActivityPhoneImageEnroll"; filename="images2.jfif"
Content-Type: image/jpeg:"",
    "FActivityPhoneImageHorizontal":"",
    "FPopUpActivityImage":"",
    "audit_cont":4,
    "ip":"",
    "saveItem":False,
    "FActivityTypeId":2,
    "FActivitySubTypeId":2,
    "FRechargeMode":1,
    "FGetMode":1,
    "FIsShowCustomerService":False,
    "FAutoJoin":0,
    "FAPPActivityType":0,
    "FAPPActivityWay":0,
    "FActivityMode":1,
    "FStatus":1,
    "FBeginTime":"2020/07/14 02:00:00",
    "FEndTime":"2020/07/15 02:00:00",
    "FActivityContext":0,
    "FAuditOption":4,
    "FIsLimitPercent":False,
    "FLimitPercent":"",
    "FIsRebateLimit":False,
    "FIsLimitIP":False,
    "FIpArray":"",
    "FVersion":0,
    "FCodeType":1,
    "FIsSetSingleAmount":True,
    "stage":"",
    "FSingleBonusAmount":10,
    "FSingleBonusLimit":10,
    "FIsSetTotalAmount":False,
    "FBonusTotalAmount":0,
    "FActivityListSort":99,
    "FGameIds":320,
    "FDomainName":"",
    "ffirstagentids":"",
    "FAccountReAmount":"",
    "FAccountReCount":"",
    "FAccountCurtReAmount":"",
    "FAccountCurtReCount":"",
    "FAccountRegisterStartDate":"",
    "FAccountRegisterEndDate":"",
    "homeView":"haocai",
    "FPhoneTemplates":"",
    "FCycle":0,
    "FIsReAmount":False,
    "FIsBet":False,
    "FReAmount":0,
    "FTotalBet":0,
    "FStyle":1,
    "activitySignDetail":{"FirstForceDailog":0,"FDayRechargeNeed":"0","FDayRechargeType":"0","FDayRechargeMoney":"1","FDayBetNeed":"0","FDayBetMoney":"1","FRetroactiveEnable":0,"FRetroactiveType":"0","FRetroactiveMoney":"1","FSignSetJson":"[{\"SignDays\":\"1\",\"SignAward\":\"5\",\"SignLimit\":\"5\"}]"},
    "FReceiveNumber":0,
    "FDescription":"",
    "FHtmlDescription":"Q",
    "FMHtmlDescription":"Q"
}'''
